### ISSUE TITLE
Asset data structure design

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/datahub#28]
Design notes / discussion for the main Datahub Asset class.

Common Standards Monitoring
-------------------------------
- What are CSM collections for?
- Are CMS data assets reports? Currently they're 'series' - how are genuine series going to be handled by the data structure?

General design
----------------
- Data Format is currently missing

**Comment by mattdebont** [comment]
The collections aren't important right now so can ignore, just me sketching out an idea of how to represent the data.

The CSM itself is a series (i.e. the collection would be a series) the individual things I guess would end up being publications for the most part I imagine

Data format is a factor of the individual data files rather than the asset as a whole so would need to be per file, currently I am just exposing the content-type but we need a better way of doing this in general.

**Comment by PeteMontgomery** [comment]
Question about the mocked-up 'application/pdf' file formats. From an 'output' perspective, it's useful, but the **file size** would be even more useful. From an 'input' perspective, how does the database get this knowledge? (How does it get into the database?)
