### ISSUE TITLE
Google tag manager

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/datahub#75]
Track downloads - file name and size

**Comment by mattdebont** [comment]
Have created a Tag manager account for the datahub that will record data downloads we need to decide on how we are going to mark download links so that they can be picked up by GTM, already should be able to pick up file sizes if a html5 data attribute exists on the link, but we will need to isolate what a download link looks like here i.e. tag them with something as not all download links are going to go to data.jncc.gov.uk

**Comment by mattdebont** [comment]
Also need to consider what to do with 'corpulent' data downloads here
