### ISSUE TITLE
Search index snapshots

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/datahub#88]
Amazon Elasticsearch Service automatcally takes daily snapshots. We should go through the process of restoring the cluster once to check any potential issues. https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains-snapshots.html#es-managedomains-snapshot-restore

**Comment by PeteMontgomery** [comment]
There's docs here https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createupdatedomains.html#es-createdomain-configure-snapshots

**Comment by LynnHeeley** [comment]
needs to be done before live. how to use them and how to restore

**Comment by felixMasonJncc** [comment]
Working with snapshots:

https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains-snapshots.html

**Comment by felixMasonJncc** [comment]
Test plan for single index and all index restore here: [http://jncc-wiki/Technical_Information/AWS_Elasticsearch_backup_test_plan]

#Outstanding
- Test restore of all indexes? (Do we want to do this - it's in the test plan if we need to). It needs consideration and will need a day when data isn't written to the index (can pause the handler)
- Restoring an index from an auto snapshot will bring it back to it the state it was in at the start of the day.
-- What about data since then? Reindex? If so what about datahub - and instructions for each system needed as part of the index recovery doc
